language: python
python:
  - "3.9"
addons:
  chrome: stable
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.1/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - python app.py &
  - google-chrome-stable --headless --disable-gpu http://localhost &
script:
  - pytest
